var fakeUsers = [{"name":"Andrew Day","email":"aday0@nasa.gov"},
{"name":"Margaret Watkins","email":"mwatkins1@loc.gov"},
{"name":"Joseph Perkins","email":"jperkins2@vimeo.com"},
{"name":"Linda Turner","email":"lturner3@cnet.com"},
{"name":"Robert Mendoza","email":"rmendoza4@behance.net"},
{"name":"Larry Burns","email":"lburns5@google.com.hk"},
{"name":"Jesse Ford","email":"jford6@webeden.co.uk"},
{"name":"Elizabeth Reynolds","email":"ereynolds7@tripod.com"},
{"name":"Katherine Simmons","email":"ksimmons8@unc.edu"},
{"name":"Melissa Simmons","email":"msimmons9@amazon.de"},
{"name":"Mark Dixon","email":"mdixona@chronoengine.com"},
{"name":"Eric Ortiz","email":"eortizb@webs.com"},
{"name":"Edward Howard","email":"ehowardc@privacy.gov.au"},
{"name":"Julia Rose","email":"jrosed@virginia.edu"},
{"name":"Dennis Wells","email":"dwellse@bbb.org"},
{"name":"Stephanie Jones","email":"sjonesf@hostgator.com"},
{"name":"Beverly Vasquez","email":"bvasquezg@hao123.com"},
{"name":"Joshua Jacobs","email":"jjacobsh@kickstarter.com"},
{"name":"Rose Mcdonald","email":"rmcdonaldi@webmd.com"},
{"name":"Christine Butler","email":"cbutlerj@intel.com"},
{"name":"Tina Kennedy","email":"tkennedyk@census.gov"},
{"name":"Antonio Chavez","email":"achavezl@youku.com"},
{"name":"Ann Jordan","email":"ajordanm@loc.gov"},
{"name":"Marie Fernandez","email":"mfernandezn@nih.gov"},
{"name":"Howard Fernandez","email":"hfernandezo@1688.com"},
{"name":"Daniel Russell","email":"drussellp@harvard.edu"},
{"name":"Steven Jones","email":"sjonesq@prweb.com"},
{"name":"Stephen Robinson","email":"srobinsonr@purevolume.com"},
{"name":"Carolyn Watkins","email":"cwatkinss@hc360.com"},
{"name":"Janice Stevens","email":"jstevenst@xing.com"},
{"name":"Shirley Gonzalez","email":"sgonzalezu@google.cn"},
{"name":"Henry Gonzalez","email":"hgonzalezv@state.tx.us"},
{"name":"Clarence Coleman","email":"ccolemanw@blogtalkradio.com"},
{"name":"Catherine Bennett","email":"cbennettx@goo.ne.jp"},
{"name":"Jacqueline Hanson","email":"jhansony@cloudflare.com"},
{"name":"Frank Rice","email":"fricez@github.com"},
{"name":"Lisa Owens","email":"lowens10@paypal.com"},
{"name":"Ronald Powell","email":"rpowell11@cloudflare.com"},
{"name":"Brandon Burns","email":"bburns12@sciencedirect.com"},
{"name":"Anna Berry","email":"aberry13@nature.com"},
{"name":"Fred Ellis","email":"fellis14@wikispaces.com"},
{"name":"Brian Roberts","email":"broberts15@fema.gov"},
{"name":"Marie Mcdonald","email":"mmcdonald16@sfgate.com"},
{"name":"Steven Ferguson","email":"sferguson17@miibeian.gov.cn"},
{"name":"Ashley Collins","email":"acollins18@noaa.gov"},
{"name":"Patrick Carpenter","email":"pcarpenter19@163.com"},
{"name":"Mildred Long","email":"mlong1a@altervista.org"},
{"name":"Harold Wells","email":"hwells1b@toplist.cz"},
{"name":"Nicole Boyd","email":"nboyd1c@hc360.com"},
{"name":"Eugene Hunt","email":"ehunt1d@wired.com"}]
var fakeLevels = [{"title":"odio","map":"ZOWYBoZ21VGs"}] /*,
{"title":"enim blandit mi","map":"aQ5Y5iHGWU"},
{"title":"purus","map":"KKNiDC9ZZF"},
{"title":"ut massa volutpat convallis","map":"EVl4fIScsjLf"},
{"title":"risus semper porta","map":"gXW6YX6"},
{"title":"neque","map":"BXAaiARTqM"},
{"title":"erat nulla tempus vivamus in","map":"L455ie"},
{"title":"quis turpis sed ante vivamus","map":"iRWf2wAOsj"},
{"title":"id mauris vulputate elementum nullam","map":"6DXqT4czL8B"},
{"title":"amet eros suspendisse accumsan","map":"upA7llmG"},
{"title":"lacinia","map":"LdxADXVmy1pQ"},
{"title":"suspendisse potenti in eleifend quam","map":"FvbbLq1pbT"},
{"title":"dolor","map":"MRYWMP8WlZ"},
{"title":"gravida","map":"JnpBoFd6A4s"},
{"title":"rhoncus","map":"e8SHhKaylZm"},
{"title":"fermentum donec","map":"dSKJv3"},
{"title":"scelerisque mauris sit amet eros","map":"fUuNDFXhK"},
{"title":"turpis sed ante vivamus tortor","map":"SZARWfxd"},
{"title":"ut erat id","map":"lFqKAsNYM"},
{"title":"et magnis","map":"o28EZKtDJn"},
{"title":"tincidunt nulla mollis molestie lorem","map":"HTKGmlEuq4Y"},
{"title":"ante vestibulum","map":"Xy7XCIIsWi"},
{"title":"semper sapien a","map":"7TVaF3lqKvQ7"},
{"title":"aliquet","map":"d10TZY40ZA"},
{"title":"lacus","map":"Yupqip"},
{"title":"tellus","map":"YHRTymz"},
{"title":"odio odio elementum eu","map":"xUD2GW2"},
{"title":"sit amet justo","map":"qTAqlf7lPbj"},
{"title":"mi pede","map":"vzpdLGQo5"},
{"title":"diam nam","map":"u4aoqvJaRCk"},
{"title":"tempus vivamus","map":"pP7lpNIdy6"},
{"title":"dui luctus rutrum nulla tellus","map":"RdwD3Y"},
{"title":"vestibulum ante ipsum primis","map":"jeE5hiqbDgHT"},
{"title":"metus","map":"khs9q0V7"},
{"title":"vestibulum ante ipsum","map":"BZzlBoU"},
{"title":"penatibus et magnis","map":"9bL6Goizl0vp"},
{"title":"ipsum dolor sit amet consectetuer","map":"49TGoZ"},
{"title":"donec quis","map":"chiSvr"},
{"title":"vulputate luctus cum","map":"eD6glx"},
{"title":"ligula sit amet","map":"ZsCUpGLRcz1m"},
{"title":"quam fringilla rhoncus mauris enim","map":"Z8xueA9Up"},
{"title":"curae mauris viverra","map":"9zX5zz"},
{"title":"turpis enim","map":"A3z4OsWfOk"},
{"title":"natoque penatibus et magnis","map":"IVhYrZ"},
{"title":"placerat","map":"3IM9aWCUI"},
{"title":"nulla dapibus dolor vel est","map":"Y1WUMw"},
{"title":"lacinia","map":"NBlu9zT6kUC"},
{"title":"iaculis justo","map":"dFt8vJ"},
{"title":"consequat metus sapien ut nunc","map":"TEP30qwuRp"},
{"title":"amet nulla","map":"RAB2Bgkul"},
{"title":"habitasse platea dictumst maecenas","map":"JZ6zCM"},
{"title":"scelerisque mauris","map":"hoSHCm7SfvYY"},
{"title":"primis in","map":"SuNWx0wWe"},
{"title":"nec euismod scelerisque","map":"34vOkHZGE"},
{"title":"blandit mi in","map":"WVgjIe"},
{"title":"at nunc commodo placerat praesent","map":"bsgnrSrd7"},
{"title":"facilisi","map":"0RHCacScfFL"},
{"title":"volutpat in congue etiam","map":"T8p4oJSGA"},
{"title":"ut suscipit a feugiat et","map":"eYCOaMiUz"},
{"title":"gravida sem","map":"AVUVSXow"},
{"title":"rhoncus aliquam lacus morbi quis","map":"qkJa8Bo"},
{"title":"aliquet pulvinar sed nisl nunc","map":"8vqKRxvbw"},
{"title":"montes nascetur ridiculus mus vivamus","map":"DorOnE9pV"},
{"title":"vivamus","map":"Gzf2daleZD"},
{"title":"magnis dis","map":"4KOR1iiWY"},
{"title":"nulla integer pede justo","map":"wmggppEnytIs"},
{"title":"ut","map":"dgra9Adf"},
{"title":"elementum in hac habitasse platea","map":"9hlw0gc"},
{"title":"habitasse platea dictumst","map":"AdQLYV"},
{"title":"at vulputate vitae nisl aenean","map":"0QHfPYnybU"},
{"title":"natoque penatibus et magnis","map":"xqnbZwkH"},
{"title":"potenti cras in purus","map":"FEZlI1"},
{"title":"praesent lectus vestibulum","map":"0vhbpEtR"},
{"title":"ornare imperdiet sapien","map":"HQpJ8b"},
{"title":"donec quis","map":"CSMlmeZZk"},
{"title":"magna vestibulum","map":"Y3x76wJr2"},
{"title":"vestibulum","map":"JfgXnw1l"},
{"title":"ultrices phasellus id sapien","map":"NLfGV2Vdd1"},
{"title":"sed vel enim","map":"Due6t1khiDc"},
{"title":"auctor gravida sem praesent id","map":"8Lb025QeB"},
{"title":"amet","map":"7ZnYx6fnB5tD"},
{"title":"in felis donec semper","map":"F6KZoLGCJQEt"},
{"title":"diam id ornare imperdiet","map":"PLWfASB"},
{"title":"ultricies","map":"oI20MuJQh2"},
{"title":"eget elit","map":"zr17DeEKK"},
{"title":"in eleifend quam","map":"2RxBdHCsl8M3"},
{"title":"sodales","map":"9kXfq0zZ"},
{"title":"parturient montes","map":"DTNeiLHSpSbq"},
{"title":"sed nisl nunc","map":"j1CoAivz"},
{"title":"quis libero","map":"O1yqsrA38n"},
{"title":"dictumst morbi vestibulum","map":"7Hcv6C0l"},
{"title":"in purus eu magna vulputate","map":"klcquW"},
{"title":"integer aliquet","map":"aL07VpRc1r"},
{"title":"malesuada in imperdiet et","map":"wxCklM78DP"},
{"title":"ultrices posuere cubilia","map":"YlMvFxJWSAfp"},
{"title":"vel est","map":"d6G27KeF"},
{"title":"est et","map":"tr4La9"},
{"title":"mauris ullamcorper purus","map":"g0RMM1s"},
{"title":"amet turpis elementum ligula","map":"a6c81QuX"},
{"title":"imperdiet nullam orci","map":"dJoH9SqwLF5n"},
{"title":"sapien","map":"HMHVi18c"},
{"title":"sagittis dui vel","map":"AFqy51"},
{"title":"magnis","map":"PjAapPT5N"},
{"title":"augue vel accumsan tellus nisi","map":"lrJpq0mSq4M"},
{"title":"in tempus","map":"6u7gIV"},
{"title":"dis parturient montes","map":"yB5mt0eR7BL"},
{"title":"magna vulputate","map":"EWfjsM1kh4"},
{"title":"nisi nam ultrices libero non","map":"4tXOTyZEaTOy"},
{"title":"ante ipsum","map":"7mqN1NGU"},
{"title":"blandit","map":"y73lCYsh"},
{"title":"dui","map":"e2Mc32HkO"},
{"title":"nulla","map":"Bj6UYds0Y"},
{"title":"pede venenatis","map":"C5PyL6"},
{"title":"adipiscing","map":"2lJ6f6"},
{"title":"sit amet","map":"N8PaonSr"},
{"title":"est risus auctor sed tristique","map":"N8F2j2"},
{"title":"turpis donec posuere metus vitae","map":"0h3dgnt"},
{"title":"donec vitae nisi nam ultrices","map":"mSUmqV"},
{"title":"nam ultrices libero non mattis","map":"mTh53Alq"},
{"title":"luctus cum","map":"7KNFVk9JQ9g"},
{"title":"cras","map":"94SO1OJ3t"},
{"title":"non velit donec diam","map":"kGKGNTxL"},
{"title":"ultricies eu nibh quisque id","map":"d1suaVw"},
{"title":"neque libero convallis eget","map":"mKl6hxsU"},
{"title":"libero quis","map":"FipyX2r"},
{"title":"quam pharetra","map":"iazbObsW"},
{"title":"non mattis pulvinar nulla","map":"leLrenyy"},
{"title":"ultrices","map":"wr3skKwYLbDO"},
{"title":"nibh ligula nec sem","map":"se3ezj7C56wp"},
{"title":"eget tincidunt eget tempus vel","map":"sFewxaF1Kr"},
{"title":"nulla ac enim in tempor","map":"HyHVCq"},
{"title":"condimentum curabitur in","map":"NRgQVFzZPaEB"},
{"title":"nisl aenean lectus","map":"4NL1BCaT5"},
{"title":"in magna bibendum","map":"0hKcYF"},
{"title":"vel est donec odio justo","map":"XG1Ric5J"},
{"title":"volutpat","map":"tzAxPxGM"},
{"title":"suspendisse potenti nullam porttitor lacus","map":"X5qFHw3i2Jv2"},
{"title":"ultrices posuere","map":"rsSXEwW"},
{"title":"eu sapien cursus","map":"n9MIpxwIUGdD"},
{"title":"nunc proin at turpis a","map":"qMOBZjdPr1J"},
{"title":"sed justo pellentesque","map":"bPwxcUqO"},
{"title":"ut ultrices","map":"isfc1lkdzcFz"},
{"title":"justo","map":"e1TRvKeQgP"},
{"title":"primis","map":"f4LTFUFEX"},
{"title":"diam erat","map":"j5Tzz0"},
{"title":"morbi porttitor lorem id","map":"fWpMKvIH"},
{"title":"viverra eget congue","map":"ao0JSscb32Sa"},
{"title":"erat tortor sollicitudin mi","map":"siIfzkuzxa"},
{"title":"et","map":"UDz12ZoZ5NOt"},
{"title":"at nibh","map":"vea7GmV6muT"},
{"title":"eget elit","map":"HulyfQt"},
{"title":"condimentum neque sapien placerat","map":"KIICM83"},
{"title":"vel","map":"ejGobQpe"},
{"title":"volutpat","map":"NdzunY7pHp"},
{"title":"pretium","map":"iz0T71mNUIm"},
{"title":"ante ipsum primis in faucibus","map":"nk4egMny"},
{"title":"faucibus orci","map":"AfQSh5d4f"},
{"title":"sapien urna pretium nisl ut","map":"1u9rzy"},
{"title":"sem duis aliquam convallis","map":"DQJCiOZaysxq"},
{"title":"varius ut blandit non","map":"ZuxEPd"},
{"title":"sapien varius ut","map":"Wzq0nu"},
{"title":"odio elementum eu interdum","map":"j6R00EvXV"},
{"title":"sollicitudin","map":"ONNA6Wbq8"},
{"title":"tincidunt nulla mollis molestie lorem","map":"beHZkfov2h"},
{"title":"condimentum","map":"Pjinj4Re"},
{"title":"eget","map":"431jz9"},
{"title":"congue risus semper","map":"L2KPPa1bY"},
{"title":"dui","map":"wcOkBIf4bZ"},
{"title":"aliquam","map":"Cb82q5nfvG2t"},
{"title":"consequat metus sapien ut nunc","map":"dovpRgS9wxJw"},
{"title":"viverra diam vitae quam","map":"e4AoT5iDl"},
{"title":"nam ultrices libero non mattis","map":"RC7JpKa"},
{"title":"sit","map":"zWTC4gmqcXS0"},
{"title":"non quam","map":"g0Wpeez"},
{"title":"maecenas leo odio condimentum","map":"lUhh8WVKm"},
{"title":"luctus rutrum nulla","map":"oi6QGwK"},
{"title":"a","map":"ZDRlI3fBM6t6"},
{"title":"ligula","map":"jJ73hpvTNROt"},
{"title":"eu","map":"tG8jyXFJrmQ"},
{"title":"at turpis donec","map":"vvorVxw"},
{"title":"praesent blandit lacinia erat","map":"pfQrEs"},
{"title":"morbi sem mauris laoreet ut","map":"pcPjibeu"},
{"title":"odio","map":"HZmiDBvWm"},
{"title":"accumsan odio curabitur convallis","map":"2eUQWPcdpT"},
{"title":"proin leo odio porttitor id","map":"sQlPYYi"},
{"title":"ipsum dolor sit amet consectetuer","map":"4aJcAw9WKx3V"},
{"title":"eu","map":"PQO7VsHjJXV"},
{"title":"mattis odio","map":"1trJmnWz"},
{"title":"lobortis ligula","map":"Z5avIFaXLR"},
{"title":"cursus vestibulum","map":"s1QPUVOF6KD"},
{"title":"consequat in","map":"HddoCEw"},
{"title":"eu","map":"r940sBnhZpt"},
{"title":"ornare imperdiet","map":"Kf4IDu3uJ"},
{"title":"felis ut","map":"Ud3FST"},
{"title":"in quis justo maecenas rhoncus","map":"uJQ3auedzbB"},
{"title":"sit amet turpis elementum","map":"bblqS8O6"},
{"title":"lorem","map":"FvtvL8jopC15"},
{"title":"rutrum nulla tellus","map":"fi788AEjDh"},
{"title":"dui","map":"ps24YinKFl"},
{"title":"in purus","map":"VEVsrmMhq"},
{"title":"maecenas tincidunt lacus at velit","map":"QpY45Zh"},
{"title":"a suscipit nulla elit","map":"i37f1tPGGe"},
{"title":"curae donec pharetra magna","map":"mwKKwarAjtj"},
{"title":"morbi non lectus aliquam","map":"Cr2fFEygU"},
{"title":"nisl aenean lectus pellentesque eget","map":"VYMZXavkIxbS"},
{"title":"pede ac diam","map":"U1CF8cciI4h1"},
{"title":"luctus rutrum nulla tellus in","map":"7lL75wn3wBEu"},
{"title":"porttitor pede justo eu","map":"fYe1t5Y"},
{"title":"semper rutrum nulla","map":"MOqQH8"},
{"title":"id sapien","map":"15Ng90"},
{"title":"ut","map":"xwdE5FTC00V"},
{"title":"interdum","map":"anjCSa"},
{"title":"tortor","map":"RDIM18dM"},
{"title":"in quis justo maecenas","map":"G4L1o13s"},
{"title":"suspendisse","map":"o87ZnOtD0"},
{"title":"enim","map":"kU9cuhWrh5f4"},
{"title":"justo in blandit","map":"209sQ5Ha"},
{"title":"turpis sed ante vivamus","map":"KQ7VTqxM21"},
{"title":"mollis molestie lorem quisque","map":"btLf9Yxltqds"},
{"title":"magna vestibulum","map":"i6IWgB0ku"},
{"title":"maecenas rhoncus","map":"6FkhLH"},
{"title":"ac nibh fusce lacus","map":"dooaQqkzheN"},
{"title":"blandit ultrices enim lorem","map":"vZcDOahCOU"},
{"title":"velit vivamus vel","map":"cPFddlkiaYJ"},
{"title":"in","map":"qgwNUh"},
{"title":"lobortis sapien sapien non mi","map":"KlE00Dy7Wi"},
{"title":"semper porta volutpat quam pede","map":"6gONqOTPrI"},
{"title":"nulla nunc purus","map":"UpwoeQmp"},
{"title":"eget orci","map":"RYSGaAhWoaLd"},
{"title":"lectus pellentesque at nulla","map":"cfsU2xNenI1"},
{"title":"vestibulum ante ipsum primis","map":"pKfCD13oUvKz"},
{"title":"ultrices","map":"Qm80AawcVy0f"},
{"title":"morbi quis","map":"aOcmv2ki"},
{"title":"accumsan","map":"sReuHxeXpG"},
{"title":"aenean","map":"ej102kz"},
{"title":"integer","map":"QF5kbx"},
{"title":"ut","map":"mova3A"},
{"title":"lacinia","map":"cJ3elpqze22"},
{"title":"est","map":"VJfvrurnQ"},
{"title":"integer a nibh","map":"lIQS6hPZX"},
{"title":"id ornare","map":"ucvt5llL1W"},
{"title":"libero convallis eget eleifend luctus","map":"Xg45am"},
{"title":"pellentesque eget nunc donec","map":"FSZTIy"},
{"title":"habitasse platea","map":"1FFzkxm0n"},
{"title":"turpis a pede","map":"5h6DRsQouTfx"},
{"title":"amet nulla","map":"bkxzrE3cSv"},
{"title":"faucibus cursus","map":"YpCiZHitz0uL"},
{"title":"sollicitudin mi sit amet lobortis","map":"lH9TfkllpJr1"},
{"title":"turpis","map":"hsPzvEAkYxP"},
{"title":"amet consectetuer adipiscing elit","map":"m009yihzL"},
{"title":"turpis nec euismod scelerisque quam","map":"xgbELkodzV"},
{"title":"penatibus et magnis dis parturient","map":"Myxw3lv"},
{"title":"tristique in","map":"VIqfiRRvFC25"},
{"title":"purus","map":"teeyR9LL"},
{"title":"turpis donec posuere metus vitae","map":"dV28XqpZ"},
{"title":"tellus in sagittis dui","map":"cUl589NV9909"},
{"title":"vestibulum ac est","map":"Q4vxbEYg"},
{"title":"cras mi pede malesuada","map":"janCQ0T7HQg"},
{"title":"pede posuere nonummy integer","map":"XHxsYhtcPD"},
{"title":"vestibulum ac est lacinia","map":"fiTCjkprNsX"},
{"title":"sem duis aliquam convallis","map":"iCfMsj7c4"},
{"title":"dolor sit","map":"65Sh1cGdy"},
{"title":"ligula sit amet","map":"CQsIVjXkMNh3"},
{"title":"malesuada in","map":"EkxOsEd"},
{"title":"in faucibus orci","map":"ZdkdLSOJp5N"},
{"title":"sit","map":"Dj6Dr6OOs0Ox"},
{"title":"erat tortor sollicitudin mi","map":"WkGXn9n5X"},
{"title":"donec pharetra","map":"J3aba8EGDT"},
{"title":"justo in hac habitasse platea","map":"ov6DiaqC0BQ"},
{"title":"nunc purus phasellus","map":"TEvMiKcSQAB"},
{"title":"accumsan tellus","map":"9hlKbE8OKH"},
{"title":"tellus in sagittis","map":"e1IcYT3tr"},
{"title":"sapien","map":"B48u9w"},
{"title":"elementum ligula","map":"Uhe1pP4wTIQN"},
{"title":"morbi non lectus aliquam","map":"bZIDB4A6KJ"},
{"title":"proin leo odio","map":"83mzoS"},
{"title":"metus sapien ut nunc","map":"GPG7BHRh"},
{"title":"ipsum dolor sit","map":"zrvh3Fa40"},
{"title":"id consequat in","map":"ixu2bQ64d3y8"},
{"title":"urna pretium nisl","map":"WvDOaUOc"},
{"title":"tempus vivamus in","map":"z0BzSG9HD"},
{"title":"ultrices erat tortor sollicitudin mi","map":"Lw18xB68a"},
{"title":"diam","map":"FylKPpAZVH"},
{"title":"sollicitudin mi sit","map":"2t0Bm7Bj6"},
{"title":"libero","map":"9OUj0q1E8XD"},
{"title":"augue","map":"tkQZTvU"},
{"title":"aliquet pulvinar","map":"id3Yuu7d9pC"},
{"title":"in imperdiet et commodo vulputate","map":"nkaTUqoXWN1i"},
{"title":"lectus in quam fringilla","map":"cjzv23Q6t"},
{"title":"augue aliquam erat","map":"h2dX56rhmc1"},
{"title":"aliquet","map":"RfEe0x"},
{"title":"quis orci","map":"lIlcpNmAYN"},
{"title":"sit amet consectetuer","map":"HzdzVdb"},
{"title":"volutpat convallis morbi odio odio","map":"LtZUACrbo"},
{"title":"pellentesque ultrices mattis odio","map":"eBzSaE"},
{"title":"erat curabitur gravida","map":"t154B1Jk53s"},
{"title":"integer a","map":"6HTYqSs"},
{"title":"metus","map":"IrkGQJEPMkY"},
{"title":"at vulputate","map":"IdZIKD"},
{"title":"lacus","map":"7GTZvn"}];
*/


//fake data at top because of hoisting issues
const mongoose = require('mongoose');
const Promise = require('bluebird');
const connectToDb = require('./index.js');
const User = mongoose.model('User');
const Level = mongoose.model('Level');

connectToDb.then(function() {
	var before = Date.now();
	User.create(fakeUsers).then(function() {
		console.log(Date.now() - before);
		var matchedGamesToUsers = fakeLevels.map(function(level) {
			return User.findOne({name: fakeUsers[Math.floor(Math.random() * fakeUsers.length)].name})
			.then(function(foundUser) {
				level.creator = foundUser._id;
				return level;
			});
		})
		return Promise.all(matchedGamesToUsers);
	})
	.then(function(levelArr) {
		return Level.create(levelArr);
	}).then(function() {
		console.log('seeded');
		console.log(Date.now() - before);
		process.kill(0);
	}).then(null, function(e) {
		console.error(e);
		process.kill(0);
	});
});
